//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegradorWebService.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://vpsrv.visualset.com.br/PostagemVipp.asmx")]
        public string IntegradorWebService_WSVIPP_PostagemVipp {
            get {
                return ((string)(this["IntegradorWebService_WSVIPP_PostagemVipp"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://vipp.visualset.com.br")]
        public string Site {
            get {
                return ((string)(this["Site"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PEFycmF5T2ZGb3JtYXRhY2FvUGxhbmlsaGE+PEZvcm1hdGFjYW9QbGFuaWxoYT48Tm9tZUF0cmlidXRvP" +
            "k9ic2VydmFjYW8xPC9Ob21lQXRyaWJ1dG8+PENvbHVuYT4xPC9Db2x1bmE+PFRhbWFuaG8+MDwvVGFtY" +
            "W5obz48RGVsaW1pdGFkb3IvPjwvRm9ybWF0YWNhb1BsYW5pbGhhPjxGb3JtYXRhY2FvUGxhbmlsaGE+P" +
            "E5vbWVBdHJpYnV0bz5RdWFudGlkYWRlPC9Ob21lQXRyaWJ1dG8+PENvbHVuYT4xMTwvQ29sdW5hPjxUY" +
            "W1hbmhvPjA8L1RhbWFuaG8+PERlbGltaXRhZG9yLz48L0Zvcm1hdGFjYW9QbGFuaWxoYT48Rm9ybWF0Y" +
            "WNhb1BsYW5pbGhhPjxOb21lQXRyaWJ1dG8+Q29udGV1ZG88L05vbWVBdHJpYnV0bz48Q29sdW5hPjEwP" +
            "C9Db2x1bmE+PFRhbWFuaG8+MDwvVGFtYW5obz48RGVsaW1pdGFkb3IvPjwvRm9ybWF0YWNhb1BsYW5pb" +
            "GhhPjxGb3JtYXRhY2FvUGxhbmlsaGE+PE5vbWVBdHJpYnV0bz5PYnNlcnZhY2FvMjwvTm9tZUF0cmlid" +
            "XRvPjxDb2x1bmE+MTM8L0NvbHVuYT48VGFtYW5obz4wPC9UYW1hbmhvPjxEZWxpbWl0YWRvci8+PC9Gb" +
            "3JtYXRhY2FvUGxhbmlsaGE+PEZvcm1hdGFjYW9QbGFuaWxoYT48Tm9tZUF0cmlidXRvPkRlc3RpbmF0Y" +
            "XJpbzwvTm9tZUF0cmlidXRvPjxDb2x1bmE+MTU8L0NvbHVuYT48VGFtYW5obz4wPC9UYW1hbmhvPjxEZ" +
            "WxpbWl0YWRvci8+PC9Gb3JtYXRhY2FvUGxhbmlsaGE+PEZvcm1hdGFjYW9QbGFuaWxoYT48Tm9tZUF0c" +
            "mlidXRvPkRvY3VtZW50b0Rlc3RpbmF0YXJpbzwvTm9tZUF0cmlidXRvPjxDb2x1bmE+MTY8L0NvbHVuY" +
            "T48VGFtYW5obz4wPC9UYW1hbmhvPjxEZWxpbWl0YWRvci8+PC9Gb3JtYXRhY2FvUGxhbmlsaGE+PEZvc" +
            "m1hdGFjYW9QbGFuaWxoYT48Tm9tZUF0cmlidXRvPkVuZGVyZWNvPC9Ob21lQXRyaWJ1dG8+PENvbHVuY" +
            "T4xNzwvQ29sdW5hPjxUYW1hbmhvPjA8L1RhbWFuaG8+PERlbGltaXRhZG9yLz48L0Zvcm1hdGFjYW9Qb" +
            "GFuaWxoYT48Rm9ybWF0YWNhb1BsYW5pbGhhPjxOb21lQXRyaWJ1dG8+TnVtZXJvPC9Ob21lQXRyaWJ1d" +
            "G8+PENvbHVuYT4xODwvQ29sdW5hPjxUYW1hbmhvPjA8L1RhbWFuaG8+PERlbGltaXRhZG9yLz48L0Zvc" +
            "m1hdGFjYW9QbGFuaWxoYT48Rm9ybWF0YWNhb1BsYW5pbGhhPjxOb21lQXRyaWJ1dG8+QmFpcnJvPC9Ob" +
            "21lQXRyaWJ1dG8+PENvbHVuYT4xOTwvQ29sdW5hPjxUYW1hbmhvPjA8L1RhbWFuaG8+PERlbGltaXRhZ" +
            "G9yLz48L0Zvcm1hdGFjYW9QbGFuaWxoYT48Rm9ybWF0YWNhb1BsYW5pbGhhPjxOb21lQXRyaWJ1dG8+Q" +
            "29tcGxlbWVudG88L05vbWVBdHJpYnV0bz48Q29sdW5hPjIwPC9Db2x1bmE+PFRhbWFuaG8+MDwvVGFtY" +
            "W5obz48RGVsaW1pdGFkb3IvPjwvRm9ybWF0YWNhb1BsYW5pbGhhPjxGb3JtYXRhY2FvUGxhbmlsaGE+P" +
            "E5vbWVBdHJpYnV0bz5DRVA8L05vbWVBdHJpYnV0bz48Q29sdW5hPjIxPC9Db2x1bmE+PFRhbWFuaG8+M" +
            "DwvVGFtYW5obz48RGVsaW1pdGFkb3IvPjwvRm9ybWF0YWNhb1BsYW5pbGhhPjxGb3JtYXRhY2FvUGxhb" +
            "mlsaGE+PE5vbWVBdHJpYnV0bz5DaWRhZGU8L05vbWVBdHJpYnV0bz48Q29sdW5hPjIyPC9Db2x1bmE+P" +
            "FRhbWFuaG8+MDwvVGFtYW5obz48RGVsaW1pdGFkb3IvPjwvRm9ybWF0YWNhb1BsYW5pbGhhPjxGb3JtY" +
            "XRhY2FvUGxhbmlsaGE+PE5vbWVBdHJpYnV0bz5VRjwvTm9tZUF0cmlidXRvPjxDb2x1bmE+MjM8L0Nvb" +
            "HVuYT48VGFtYW5obz4wPC9UYW1hbmhvPjxEZWxpbWl0YWRvci8+PC9Gb3JtYXRhY2FvUGxhbmlsaGE+P" +
            "EZvcm1hdGFjYW9QbGFuaWxoYT48Tm9tZUF0cmlidXRvPlNlcnZpY288L05vbWVBdHJpYnV0bz48Q29sd" +
            "W5hPjI1PC9Db2x1bmE+PFRhbWFuaG8+MDwvVGFtYW5obz48RGVsaW1pdGFkb3IvPjwvRm9ybWF0YWNhb" +
            "1BsYW5pbGhhPjwvQXJyYXlPZkZvcm1hdGFjYW9QbGFuaWxoYT4=")]
        public string LayoutCengage {
            get {
                return ((string)(this["LayoutCengage"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SaveFile {
            get {
                return ((string)(this["SaveFile"]));
            }
            set {
                this["SaveFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PEFycmF5T2ZGb3JtYXRhY2FvUGxhbmlsaGE+PEZvcm1hdGFjYW9QbGFuaWxoYT48Tm9tZUF0cmlidXRvP" +
            "kNvZGlnb0JhcnJhVm9sdW1lPC9Ob21lQXRyaWJ1dG8+PENvbHVuYT4yPC9Db2x1bmE+PEluaWNpbz4xP" +
            "C9JbmljaW8+PFRhbWFuaG8+NDwvVGFtYW5obz48RGVsaW1pdGFkb3I+OzwvRGVsaW1pdGFkb3I+PC9Gb" +
            "3JtYXRhY2FvUGxhbmlsaGE+PEZvcm1hdGFjYW9QbGFuaWxoYT48Tm9tZUF0cmlidXRvPkNvZGlnb0Jhc" +
            "nJhQ2xpZW50ZTwvTm9tZUF0cmlidXRvPjxDb2x1bmE+MzwvQ29sdW5hPjxJbmljaW8+MTI8L0luaWNpb" +
            "z48VGFtYW5obz4yPC9UYW1hbmhvPjxEZWxpbWl0YWRvcj47PC9EZWxpbWl0YWRvcj48L0Zvcm1hdGFjY" +
            "W9QbGFuaWxoYT48Rm9ybWF0YWNhb1BsYW5pbGhhPjxOb21lQXRyaWJ1dG8+T2JzZXJ2YWNhb1Zpc3Vhb" +
            "DwvTm9tZUF0cmlidXRvPjxDb2x1bmE+NDwvQ29sdW5hPjxJbmljaW8+MTU8L0luaWNpbz48VGFtYW5ob" +
            "z41PC9UYW1hbmhvPjxEZWxpbWl0YWRvcj47PC9EZWxpbWl0YWRvcj48L0Zvcm1hdGFjYW9QbGFuaWxoY" +
            "T48Rm9ybWF0YWNhb1BsYW5pbGhhPjxOb21lQXRyaWJ1dG8+Tm9tZTwvTm9tZUF0cmlidXRvPjxDb2x1b" +
            "mE+NTwvQ29sdW5hPjxJbmljaW8+MjE8L0luaWNpbz48VGFtYW5obz40MDwvVGFtYW5obz48RGVsaW1pd" +
            "GFkb3I+OzwvRGVsaW1pdGFkb3I+PC9Gb3JtYXRhY2FvUGxhbmlsaGE+PEZvcm1hdGFjYW9QbGFuaWxoY" +
            "T48Tm9tZUF0cmlidXRvPkVuZGVyZWNvPC9Ob21lQXRyaWJ1dG8+PEluaWNpbz42MjwvSW5pY2lvPjxDb" +
            "2x1bmE+NjwvQ29sdW5hPjxUYW1hbmhvPjQwPC9UYW1hbmhvPjxEZWxpbWl0YWRvcj47PC9EZWxpbWl0Y" +
            "WRvcj48L0Zvcm1hdGFjYW9QbGFuaWxoYT48Rm9ybWF0YWNhb1BsYW5pbGhhPjxOb21lQXRyaWJ1dG8+Q" +
            "mFpcnJvPC9Ob21lQXRyaWJ1dG8+PENvbHVuYT43PC9Db2x1bmE+PEluaWNpbz4xMDM8L0luaWNpbz48V" +
            "GFtYW5obz4xNTwvVGFtYW5obz48RGVsaW1pdGFkb3I+OzwvRGVsaW1pdGFkb3I+PC9Gb3JtYXRhY2FvU" +
            "GxhbmlsaGE+PEZvcm1hdGFjYW9QbGFuaWxoYT48Tm9tZUF0cmlidXRvPkNpZGFkZTwvTm9tZUF0cmlid" +
            "XRvPjxDb2x1bmE+ODwvQ29sdW5hPjxJbmljaW8+MTE5PC9JbmljaW8+PFRhbWFuaG8+MTU8L1RhbWFua" +
            "G8+PERlbGltaXRhZG9yPjs8L0RlbGltaXRhZG9yPjwvRm9ybWF0YWNhb1BsYW5pbGhhPjxGb3JtYXRhY" +
            "2FvUGxhbmlsaGE+PE5vbWVBdHJpYnV0bz5VRjwvTm9tZUF0cmlidXRvPjxDb2x1bmE+OTwvQ29sdW5hP" +
            "jxJbmljaW8+MTM1PC9JbmljaW8+PFRhbWFuaG8+MjwvVGFtYW5obz48RGVsaW1pdGFkb3I+OzwvRGVsa" +
            "W1pdGFkb3I+PC9Gb3JtYXRhY2FvUGxhbmlsaGE+PEZvcm1hdGFjYW9QbGFuaWxoYT48Tm9tZUF0cmlid" +
            "XRvPkNFUDwvTm9tZUF0cmlidXRvPjxDb2x1bmE+MTA8L0NvbHVuYT48SW5pY2lvPjEzODwvSW5pY2lvP" +
            "jxUYW1hbmhvPjEwPC9UYW1hbmhvPjxEZWxpbWl0YWRvcj47PC9EZWxpbWl0YWRvcj48L0Zvcm1hdGFjY" +
            "W9QbGFuaWxoYT48Rm9ybWF0YWNhb1BsYW5pbGhhPjxOb21lQXRyaWJ1dG8+RXRpcXVldGE8L05vbWVBd" +
            "HJpYnV0bz48Q29sdW5hPjExPC9Db2x1bmE+PEluaWNpbz4xNDk8L0luaWNpbz48VGFtYW5obz4xMzwvV" +
            "GFtYW5obz48RGVsaW1pdGFkb3I+OzwvRGVsaW1pdGFkb3I+PC9Gb3JtYXRhY2FvUGxhbmlsaGE+PC9Bc" +
            "nJheU9mRm9ybWF0YWNhb1BsYW5pbGhhPg==")]
        public string LayoutUnimed {
            get {
                return ((string)(this["LayoutUnimed"]));
            }
            set {
                this["LayoutUnimed"] = value;
            }
        }
    }
}
