//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Este código-fonte foi gerado automaticamente por Microsoft.VSDesigner, Versão 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace IntegradorWebService.WSVIPP {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="PostagemVippSoap", Namespace="http://www.visualset.inf.br/")]
    public partial class PostagemVipp : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback BloquearObjetoCorreiosOperationCompleted;
        
        private System.Threading.SendOrPostCallback BloquearDownloadConhecimentoOperationCompleted;
        
        private System.Threading.SendOrPostCallback LiberarDownloadConhecimentoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarRastreioObjetoOperationCompleted;
        
        private System.Threading.SendOrPostCallback PostarObjetoOperationCompleted;
        
        private System.Threading.SendOrPostCallback PostarObjetoObjectOperationCompleted;
        
        private System.Threading.SendOrPostCallback SolicitarEtiquetaOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public PostagemVipp() {
            this.Url = global::IntegradorWebService.Properties.Settings.Default.IntegradorWebService_WSVIPP_PostagemVipp;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event BloquearObjetoCorreiosCompletedEventHandler BloquearObjetoCorreiosCompleted;
        
        /// <remarks/>
        public event BloquearDownloadConhecimentoCompletedEventHandler BloquearDownloadConhecimentoCompleted;
        
        /// <remarks/>
        public event LiberarDownloadConhecimentoCompletedEventHandler LiberarDownloadConhecimentoCompleted;
        
        /// <remarks/>
        public event ListarRastreioObjetoCompletedEventHandler ListarRastreioObjetoCompleted;
        
        /// <remarks/>
        public event PostarObjetoCompletedEventHandler PostarObjetoCompleted;
        
        /// <remarks/>
        public event PostarObjetoObjectCompletedEventHandler PostarObjetoObjectCompleted;
        
        /// <remarks/>
        public event SolicitarEtiquetaCompletedEventHandler SolicitarEtiquetaCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.visualset.inf.br/BloquearObjetoCorreios", RequestNamespace="http://www.visualset.inf.br/", ResponseNamespace="http://www.visualset.inf.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public BloquearObjetoCorreios BloquearObjetoCorreios([System.Xml.Serialization.XmlElementAttribute("BloquearObjetoCorreios")] BloquearObjetoCorreios BloquearObjetoCorreios1) {
            object[] results = this.Invoke("BloquearObjetoCorreios", new object[] {
                        BloquearObjetoCorreios1});
            return ((BloquearObjetoCorreios)(results[0]));
        }
        
        /// <remarks/>
        public void BloquearObjetoCorreiosAsync(BloquearObjetoCorreios BloquearObjetoCorreios1) {
            this.BloquearObjetoCorreiosAsync(BloquearObjetoCorreios1, null);
        }
        
        /// <remarks/>
        public void BloquearObjetoCorreiosAsync(BloquearObjetoCorreios BloquearObjetoCorreios1, object userState) {
            if ((this.BloquearObjetoCorreiosOperationCompleted == null)) {
                this.BloquearObjetoCorreiosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBloquearObjetoCorreiosOperationCompleted);
            }
            this.InvokeAsync("BloquearObjetoCorreios", new object[] {
                        BloquearObjetoCorreios1}, this.BloquearObjetoCorreiosOperationCompleted, userState);
        }
        
        private void OnBloquearObjetoCorreiosOperationCompleted(object arg) {
            if ((this.BloquearObjetoCorreiosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BloquearObjetoCorreiosCompleted(this, new BloquearObjetoCorreiosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.visualset.inf.br/BloquearDownloadConhecimento", RequestNamespace="http://www.visualset.inf.br/", ResponseNamespace="http://www.visualset.inf.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public BloquearDownload BloquearDownloadConhecimento(BloquearDownload BloquearPostagem) {
            object[] results = this.Invoke("BloquearDownloadConhecimento", new object[] {
                        BloquearPostagem});
            return ((BloquearDownload)(results[0]));
        }
        
        /// <remarks/>
        public void BloquearDownloadConhecimentoAsync(BloquearDownload BloquearPostagem) {
            this.BloquearDownloadConhecimentoAsync(BloquearPostagem, null);
        }
        
        /// <remarks/>
        public void BloquearDownloadConhecimentoAsync(BloquearDownload BloquearPostagem, object userState) {
            if ((this.BloquearDownloadConhecimentoOperationCompleted == null)) {
                this.BloquearDownloadConhecimentoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBloquearDownloadConhecimentoOperationCompleted);
            }
            this.InvokeAsync("BloquearDownloadConhecimento", new object[] {
                        BloquearPostagem}, this.BloquearDownloadConhecimentoOperationCompleted, userState);
        }
        
        private void OnBloquearDownloadConhecimentoOperationCompleted(object arg) {
            if ((this.BloquearDownloadConhecimentoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BloquearDownloadConhecimentoCompleted(this, new BloquearDownloadConhecimentoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.visualset.inf.br/LiberarDownloadConhecimento", RequestNamespace="http://www.visualset.inf.br/", ResponseNamespace="http://www.visualset.inf.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public LiberarDownload LiberarDownloadConhecimento(LiberarDownload LiberarPostagem) {
            object[] results = this.Invoke("LiberarDownloadConhecimento", new object[] {
                        LiberarPostagem});
            return ((LiberarDownload)(results[0]));
        }
        
        /// <remarks/>
        public void LiberarDownloadConhecimentoAsync(LiberarDownload LiberarPostagem) {
            this.LiberarDownloadConhecimentoAsync(LiberarPostagem, null);
        }
        
        /// <remarks/>
        public void LiberarDownloadConhecimentoAsync(LiberarDownload LiberarPostagem, object userState) {
            if ((this.LiberarDownloadConhecimentoOperationCompleted == null)) {
                this.LiberarDownloadConhecimentoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLiberarDownloadConhecimentoOperationCompleted);
            }
            this.InvokeAsync("LiberarDownloadConhecimento", new object[] {
                        LiberarPostagem}, this.LiberarDownloadConhecimentoOperationCompleted, userState);
        }
        
        private void OnLiberarDownloadConhecimentoOperationCompleted(object arg) {
            if ((this.LiberarDownloadConhecimentoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LiberarDownloadConhecimentoCompleted(this, new LiberarDownloadConhecimentoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.visualset.inf.br/ListarRastreioObjeto", RequestNamespace="http://www.visualset.inf.br/", ResponseNamespace="http://www.visualset.inf.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ObjetoRastreio[] ListarRastreioObjeto(ListarRastreio ListarRastreio) {
            object[] results = this.Invoke("ListarRastreioObjeto", new object[] {
                        ListarRastreio});
            return ((ObjetoRastreio[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarRastreioObjetoAsync(ListarRastreio ListarRastreio) {
            this.ListarRastreioObjetoAsync(ListarRastreio, null);
        }
        
        /// <remarks/>
        public void ListarRastreioObjetoAsync(ListarRastreio ListarRastreio, object userState) {
            if ((this.ListarRastreioObjetoOperationCompleted == null)) {
                this.ListarRastreioObjetoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarRastreioObjetoOperationCompleted);
            }
            this.InvokeAsync("ListarRastreioObjeto", new object[] {
                        ListarRastreio}, this.ListarRastreioObjetoOperationCompleted, userState);
        }
        
        private void OnListarRastreioObjetoOperationCompleted(object arg) {
            if ((this.ListarRastreioObjetoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarRastreioObjetoCompleted(this, new ListarRastreioObjetoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.visualset.inf.br/PostarObjeto", RequestNamespace="http://www.visualset.inf.br/", ResponseNamespace="http://www.visualset.inf.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode PostarObjeto(Postagem PostagemVipp) {
            object[] results = this.Invoke("PostarObjeto", new object[] {
                        PostagemVipp});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void PostarObjetoAsync(Postagem PostagemVipp) {
            this.PostarObjetoAsync(PostagemVipp, null);
        }
        
        /// <remarks/>
        public void PostarObjetoAsync(Postagem PostagemVipp, object userState) {
            if ((this.PostarObjetoOperationCompleted == null)) {
                this.PostarObjetoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPostarObjetoOperationCompleted);
            }
            this.InvokeAsync("PostarObjeto", new object[] {
                        PostagemVipp}, this.PostarObjetoOperationCompleted, userState);
        }
        
        private void OnPostarObjetoOperationCompleted(object arg) {
            if ((this.PostarObjetoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PostarObjetoCompleted(this, new PostarObjetoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.visualset.inf.br/PostarObjetoObject", RequestNamespace="http://www.visualset.inf.br/", ResponseNamespace="http://www.visualset.inf.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PostagemRetorno PostarObjetoObject(Postagem PostagemVipp) {
            object[] results = this.Invoke("PostarObjetoObject", new object[] {
                        PostagemVipp});
            return ((PostagemRetorno)(results[0]));
        }
        
        /// <remarks/>
        public void PostarObjetoObjectAsync(Postagem PostagemVipp) {
            this.PostarObjetoObjectAsync(PostagemVipp, null);
        }
        
        /// <remarks/>
        public void PostarObjetoObjectAsync(Postagem PostagemVipp, object userState) {
            if ((this.PostarObjetoObjectOperationCompleted == null)) {
                this.PostarObjetoObjectOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPostarObjetoObjectOperationCompleted);
            }
            this.InvokeAsync("PostarObjetoObject", new object[] {
                        PostagemVipp}, this.PostarObjetoObjectOperationCompleted, userState);
        }
        
        private void OnPostarObjetoObjectOperationCompleted(object arg) {
            if ((this.PostarObjetoObjectCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PostarObjetoObjectCompleted(this, new PostarObjetoObjectCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.visualset.inf.br/SolicitarEtiqueta", RequestNamespace="http://www.visualset.inf.br/", ResponseNamespace="http://www.visualset.inf.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RetornoEtiquetas SolicitarEtiqueta(string NumeroCartao, string Usuario, string Senha, string CodigoServico, string Quantidade) {
            object[] results = this.Invoke("SolicitarEtiqueta", new object[] {
                        NumeroCartao,
                        Usuario,
                        Senha,
                        CodigoServico,
                        Quantidade});
            return ((RetornoEtiquetas)(results[0]));
        }
        
        /// <remarks/>
        public void SolicitarEtiquetaAsync(string NumeroCartao, string Usuario, string Senha, string CodigoServico, string Quantidade) {
            this.SolicitarEtiquetaAsync(NumeroCartao, Usuario, Senha, CodigoServico, Quantidade, null);
        }
        
        /// <remarks/>
        public void SolicitarEtiquetaAsync(string NumeroCartao, string Usuario, string Senha, string CodigoServico, string Quantidade, object userState) {
            if ((this.SolicitarEtiquetaOperationCompleted == null)) {
                this.SolicitarEtiquetaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSolicitarEtiquetaOperationCompleted);
            }
            this.InvokeAsync("SolicitarEtiqueta", new object[] {
                        NumeroCartao,
                        Usuario,
                        Senha,
                        CodigoServico,
                        Quantidade}, this.SolicitarEtiquetaOperationCompleted, userState);
        }
        
        private void OnSolicitarEtiquetaOperationCompleted(object arg) {
            if ((this.SolicitarEtiquetaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SolicitarEtiquetaCompleted(this, new SolicitarEtiquetaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.visualset.inf.br/")]
    public partial class BloquearObjetoCorreios {
        
        private PerfilVipp perfilVippField;
        
        private string etiquetaField;
        
        private Erro[] listaErrosField;
        
        /// <remarks/>
        public PerfilVipp PerfilVipp {
            get {
                return this.perfilVippField;
            }
            set {
                this.perfilVippField = value;
            }
        }
        
        /// <remarks/>
        public string Etiqueta {
            get {
                return this.etiquetaField;
            }
            set {
                this.etiquetaField = value;
            }
        }
        
        /// <remarks/>
        public Erro[] ListaErros {
            get {
                return this.listaErrosField;
            }
            set {
                this.listaErrosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.visualset.inf.br/")]
    public partial class PerfilVipp {
        
        private string usuarioField;
        
        private string tokenField;
        
        private string idPerfilField;
        
        /// <remarks/>
        public string Usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
            }
        }
        
        /// <remarks/>
        public string Token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }
        
        /// <remarks/>
        public string IdPerfil {
            get {
                return this.idPerfilField;
            }
            set {
                this.idPerfilField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.visualset.inf.br/")]
    public partial class EtiquetaPostagem {
        
        private string numeroEtiquetaField;
        
        /// <remarks/>
        public string NumeroEtiqueta {
            get {
                return this.numeroEtiquetaField;
            }
            set {
                this.numeroEtiquetaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.visualset.inf.br/")]
    public partial class RetornoEtiquetas {
        
        private EtiquetaPostagem[] etiquetasField;
        
        private Erro[] listaErrosField;
        
        private StSolicitacao stSolicitacaoField;
        
        private string statusSolicitacaoField;
        
        /// <remarks/>
        public EtiquetaPostagem[] Etiquetas {
            get {
                return this.etiquetasField;
            }
            set {
                this.etiquetasField = value;
            }
        }
        
        /// <remarks/>
        public Erro[] ListaErros {
            get {
                return this.listaErrosField;
            }
            set {
                this.listaErrosField = value;
            }
        }
        
        /// <remarks/>
        public StSolicitacao StSolicitacao {
            get {
                return this.stSolicitacaoField;
            }
            set {
                this.stSolicitacaoField = value;
            }
        }
        
        /// <remarks/>
        public string StatusSolicitacao {
            get {
                return this.statusSolicitacaoField;
            }
            set {
                this.statusSolicitacaoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.visualset.inf.br/")]
    public partial class Erro {
        
        private TipoErro tipoErroField;
        
        private string atributoField;
        
        private string descricaoField;
        
        private string mensagemField;
        
        private string stackTraceField;
        
        private string stackTraceOutField;
        
        private string origemField;
        
        /// <remarks/>
        public TipoErro TipoErro {
            get {
                return this.tipoErroField;
            }
            set {
                this.tipoErroField = value;
            }
        }
        
        /// <remarks/>
        public string Atributo {
            get {
                return this.atributoField;
            }
            set {
                this.atributoField = value;
            }
        }
        
        /// <remarks/>
        public string Descricao {
            get {
                return this.descricaoField;
            }
            set {
                this.descricaoField = value;
            }
        }
        
        /// <remarks/>
        public string Mensagem {
            get {
                return this.mensagemField;
            }
            set {
                this.mensagemField = value;
            }
        }
        
        /// <remarks/>
        public string StackTrace {
            get {
                return this.stackTraceField;
            }
            set {
                this.stackTraceField = value;
            }
        }
        
        /// <remarks/>
        public string StackTraceOut {
            get {
                return this.stackTraceOutField;
            }
            set {
                this.stackTraceOutField = value;
            }
        }
        
        /// <remarks/>
        public string Origem {
            get {
                return this.origemField;
            }
            set {
                this.origemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.visualset.inf.br/")]
    public enum TipoErro {
        
        /// <remarks/>
        Excecao,
        
        /// <remarks/>
        RegraNegocio,
        
        /// <remarks/>
        Validacao,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.visualset.inf.br/")]
    public enum StSolicitacao {
        
        /// <remarks/>
        Invalida,
        
        /// <remarks/>
        Valida,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.visualset.inf.br/")]
    public partial class PostagemRetorno {
        
        private PerfilVipp perfilVippField;
        
        private ContratoEct contratoEctField;
        
        private Destinatario destinatarioField;
        
        private Servico servicoField;
        
        private NotaFiscal[] notasFiscaisField;
        
        private VolumeObjeto[] volumesField;
        
        private Erro[] listaErrosField;
        
        private string statusPostagemField;
        
        /// <remarks/>
        public PerfilVipp PerfilVipp {
            get {
                return this.perfilVippField;
            }
            set {
                this.perfilVippField = value;
            }
        }
        
        /// <remarks/>
        public ContratoEct ContratoEct {
            get {
                return this.contratoEctField;
            }
            set {
                this.contratoEctField = value;
            }
        }
        
        /// <remarks/>
        public Destinatario Destinatario {
            get {
                return this.destinatarioField;
            }
            set {
                this.destinatarioField = value;
            }
        }
        
        /// <remarks/>
        public Servico Servico {
            get {
                return this.servicoField;
            }
            set {
                this.servicoField = value;
            }
        }
        
        /// <remarks/>
        public NotaFiscal[] NotasFiscais {
            get {
                return this.notasFiscaisField;
            }
            set {
                this.notasFiscaisField = value;
            }
        }
        
        /// <remarks/>
        public VolumeObjeto[] Volumes {
            get {
                return this.volumesField;
            }
            set {
                this.volumesField = value;
            }
        }
        
        /// <remarks/>
        public Erro[] ListaErros {
            get {
                return this.listaErrosField;
            }
            set {
                this.listaErrosField = value;
            }
        }
        
        /// <remarks/>
        public string StatusPostagem {
            get {
                return this.statusPostagemField;
            }
            set {
                this.statusPostagemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.visualset.inf.br/")]
    public partial class ContratoEct {
        
        private string nrContratoField;
        
        private string codigoAdministrativoField;
        
        private string nrCartaoField;
        
        /// <remarks/>
        public string NrContrato {
            get {
                return this.nrContratoField;
            }
            set {
                this.nrContratoField = value;
            }
        }
        
        /// <remarks/>
        public string CodigoAdministrativo {
            get {
                return this.codigoAdministrativoField;
            }
            set {
                this.codigoAdministrativoField = value;
            }
        }
        
        /// <remarks/>
        public string NrCartao {
            get {
                return this.nrCartaoField;
            }
            set {
                this.nrCartaoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.visualset.inf.br/")]
    public partial class Destinatario {
        
        private string cnpjCpfField;
        
        private string ieRgField;
        
        private string nomeField;
        
        private string segundaLinhaDestinatarioField;
        
        private string enderecoField;
        
        private string numeroField;
        
        private string complementoField;
        
        private string bairroField;
        
        private string cidadeField;
        
        private string ufField;
        
        private string cepField;
        
        private string telefoneField;
        
        private string celularField;
        
        private string emailField;
        
        /// <remarks/>
        public string CnpjCpf {
            get {
                return this.cnpjCpfField;
            }
            set {
                this.cnpjCpfField = value;
            }
        }
        
        /// <remarks/>
        public string IeRg {
            get {
                return this.ieRgField;
            }
            set {
                this.ieRgField = value;
            }
        }
        
        /// <remarks/>
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        public string SegundaLinhaDestinatario {
            get {
                return this.segundaLinhaDestinatarioField;
            }
            set {
                this.segundaLinhaDestinatarioField = value;
            }
        }
        
        /// <remarks/>
        public string Endereco {
            get {
                return this.enderecoField;
            }
            set {
                this.enderecoField = value;
            }
        }
        
        /// <remarks/>
        public string Numero {
            get {
                return this.numeroField;
            }
            set {
                this.numeroField = value;
            }
        }
        
        /// <remarks/>
        public string Complemento {
            get {
                return this.complementoField;
            }
            set {
                this.complementoField = value;
            }
        }
        
        /// <remarks/>
        public string Bairro {
            get {
                return this.bairroField;
            }
            set {
                this.bairroField = value;
            }
        }
        
        /// <remarks/>
        public string Cidade {
            get {
                return this.cidadeField;
            }
            set {
                this.cidadeField = value;
            }
        }
        
        /// <remarks/>
        public string UF {
            get {
                return this.ufField;
            }
            set {
                this.ufField = value;
            }
        }
        
        /// <remarks/>
        public string Cep {
            get {
                return this.cepField;
            }
            set {
                this.cepField = value;
            }
        }
        
        /// <remarks/>
        public string Telefone {
            get {
                return this.telefoneField;
            }
            set {
                this.telefoneField = value;
            }
        }
        
        /// <remarks/>
        public string Celular {
            get {
                return this.celularField;
            }
            set {
                this.celularField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.visualset.inf.br/")]
    public partial class Servico {
        
        private string servicoECTField;
        
        /// <remarks/>
        public string ServicoECT {
            get {
                return this.servicoECTField;
            }
            set {
                this.servicoECTField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.visualset.inf.br/")]
    public partial class NotaFiscal {
        
        private string dtNotaFiscalField;
        
        private string serieNotaFiscalField;
        
        private string nrNotaFiscalField;
        
        private string vlrTotalNotaField;
        
        /// <remarks/>
        public string DtNotaFiscal {
            get {
                return this.dtNotaFiscalField;
            }
            set {
                this.dtNotaFiscalField = value;
            }
        }
        
        /// <remarks/>
        public string SerieNotaFiscal {
            get {
                return this.serieNotaFiscalField;
            }
            set {
                this.serieNotaFiscalField = value;
            }
        }
        
        /// <remarks/>
        public string NrNotaFiscal {
            get {
                return this.nrNotaFiscalField;
            }
            set {
                this.nrNotaFiscalField = value;
            }
        }
        
        /// <remarks/>
        public string VlrTotalNota {
            get {
                return this.vlrTotalNotaField;
            }
            set {
                this.vlrTotalNotaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.visualset.inf.br/")]
    public partial class VolumeObjeto {
        
        private string pesoField;
        
        private string alturaField;
        
        private string larguraField;
        
        private string comprimentoField;
        
        private string contaLoteField;
        
        private string chaveRoteamentoField;
        
        private string codigoBarraVolumeField;
        
        private string codigoBarraClienteField;
        
        private string observacaoVisualField;
        
        private string observacaoQuatroField;
        
        private string observacaoCincoField;
        
        private string posicaoVolumeField;
        
        private string conteudoField;
        
        private DeclaracaoConteudo declaracaoConteudoField;
        
        private string valorDeclaradoField;
        
        private string adicionaisVolumeField;
        
        private string vlrACobrarField;
        
        private string etiquetaField;
        
        /// <remarks/>
        public string Peso {
            get {
                return this.pesoField;
            }
            set {
                this.pesoField = value;
            }
        }
        
        /// <remarks/>
        public string Altura {
            get {
                return this.alturaField;
            }
            set {
                this.alturaField = value;
            }
        }
        
        /// <remarks/>
        public string Largura {
            get {
                return this.larguraField;
            }
            set {
                this.larguraField = value;
            }
        }
        
        /// <remarks/>
        public string Comprimento {
            get {
                return this.comprimentoField;
            }
            set {
                this.comprimentoField = value;
            }
        }
        
        /// <remarks/>
        public string ContaLote {
            get {
                return this.contaLoteField;
            }
            set {
                this.contaLoteField = value;
            }
        }
        
        /// <remarks/>
        public string ChaveRoteamento {
            get {
                return this.chaveRoteamentoField;
            }
            set {
                this.chaveRoteamentoField = value;
            }
        }
        
        /// <remarks/>
        public string CodigoBarraVolume {
            get {
                return this.codigoBarraVolumeField;
            }
            set {
                this.codigoBarraVolumeField = value;
            }
        }
        
        /// <remarks/>
        public string CodigoBarraCliente {
            get {
                return this.codigoBarraClienteField;
            }
            set {
                this.codigoBarraClienteField = value;
            }
        }
        
        /// <remarks/>
        public string ObservacaoVisual {
            get {
                return this.observacaoVisualField;
            }
            set {
                this.observacaoVisualField = value;
            }
        }
        
        /// <remarks/>
        public string ObservacaoQuatro {
            get {
                return this.observacaoQuatroField;
            }
            set {
                this.observacaoQuatroField = value;
            }
        }
        
        /// <remarks/>
        public string ObservacaoCinco {
            get {
                return this.observacaoCincoField;
            }
            set {
                this.observacaoCincoField = value;
            }
        }
        
        /// <remarks/>
        public string PosicaoVolume {
            get {
                return this.posicaoVolumeField;
            }
            set {
                this.posicaoVolumeField = value;
            }
        }
        
        /// <remarks/>
        public string Conteudo {
            get {
                return this.conteudoField;
            }
            set {
                this.conteudoField = value;
            }
        }
        
        /// <remarks/>
        public DeclaracaoConteudo DeclaracaoConteudo {
            get {
                return this.declaracaoConteudoField;
            }
            set {
                this.declaracaoConteudoField = value;
            }
        }
        
        /// <remarks/>
        public string ValorDeclarado {
            get {
                return this.valorDeclaradoField;
            }
            set {
                this.valorDeclaradoField = value;
            }
        }
        
        /// <remarks/>
        public string AdicionaisVolume {
            get {
                return this.adicionaisVolumeField;
            }
            set {
                this.adicionaisVolumeField = value;
            }
        }
        
        /// <remarks/>
        public string VlrACobrar {
            get {
                return this.vlrACobrarField;
            }
            set {
                this.vlrACobrarField = value;
            }
        }
        
        /// <remarks/>
        public string Etiqueta {
            get {
                return this.etiquetaField;
            }
            set {
                this.etiquetaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.visualset.inf.br/")]
    public partial class DeclaracaoConteudo {
        
        private string documentoRemetenteField;
        
        private string documentoDestinatarioField;
        
        private int pesoTotalField;
        
        private ItemConteudo[] itemConteudoField;
        
        /// <remarks/>
        public string DocumentoRemetente {
            get {
                return this.documentoRemetenteField;
            }
            set {
                this.documentoRemetenteField = value;
            }
        }
        
        /// <remarks/>
        public string DocumentoDestinatario {
            get {
                return this.documentoDestinatarioField;
            }
            set {
                this.documentoDestinatarioField = value;
            }
        }
        
        /// <remarks/>
        public int PesoTotal {
            get {
                return this.pesoTotalField;
            }
            set {
                this.pesoTotalField = value;
            }
        }
        
        /// <remarks/>
        public ItemConteudo[] ItemConteudo {
            get {
                return this.itemConteudoField;
            }
            set {
                this.itemConteudoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.visualset.inf.br/")]
    public partial class ItemConteudo {
        
        private string descricaoConteudoField;
        
        private int quantidadeField;
        
        private string valorField;
        
        /// <remarks/>
        public string DescricaoConteudo {
            get {
                return this.descricaoConteudoField;
            }
            set {
                this.descricaoConteudoField = value;
            }
        }
        
        /// <remarks/>
        public int Quantidade {
            get {
                return this.quantidadeField;
            }
            set {
                this.quantidadeField = value;
            }
        }
        
        /// <remarks/>
        public string Valor {
            get {
                return this.valorField;
            }
            set {
                this.valorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.visualset.inf.br/")]
    public partial class Postagem {
        
        private PerfilVipp perfilVippField;
        
        private ContratoEct contratoEctField;
        
        private Destinatario destinatarioField;
        
        private Servico servicoField;
        
        private NotaFiscal[] notasFiscaisField;
        
        private VolumeObjeto[] volumesField;
        
        /// <remarks/>
        public PerfilVipp PerfilVipp {
            get {
                return this.perfilVippField;
            }
            set {
                this.perfilVippField = value;
            }
        }
        
        /// <remarks/>
        public ContratoEct ContratoEct {
            get {
                return this.contratoEctField;
            }
            set {
                this.contratoEctField = value;
            }
        }
        
        /// <remarks/>
        public Destinatario Destinatario {
            get {
                return this.destinatarioField;
            }
            set {
                this.destinatarioField = value;
            }
        }
        
        /// <remarks/>
        public Servico Servico {
            get {
                return this.servicoField;
            }
            set {
                this.servicoField = value;
            }
        }
        
        /// <remarks/>
        public NotaFiscal[] NotasFiscais {
            get {
                return this.notasFiscaisField;
            }
            set {
                this.notasFiscaisField = value;
            }
        }
        
        /// <remarks/>
        public VolumeObjeto[] Volumes {
            get {
                return this.volumesField;
            }
            set {
                this.volumesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.visualset.inf.br/")]
    public partial class EventoRastreio {
        
        private long idVolumeObjetoField;
        
        private long idEventoRastreioField;
        
        private string tipoEventoField;
        
        private int idStatusField;
        
        private int idStatusEventoField;
        
        private string descricaoStatusEventoField;
        
        private System.DateTime dtEventoCompletaField;
        
        private int idGrupoStatusEventoField;
        
        private string nomeGrupoStatusEventoField;
        
        private string codigoEdiField;
        
        private long idLocalEventoOrigemField;
        
        private string localEventoField;
        
        private string tipoEnderecoField;
        
        private string enderecoEventoField;
        
        private string complementoEnderecoEventoField;
        
        private string bairroEventoField;
        
        private string cidadeEventoField;
        
        private string uFEventoField;
        
        private string sTOEventoField;
        
        private long idLocalEventoDestinoField;
        
        private string destinoField;
        
        private string tipoEnderecoDestinoField;
        
        private string enderecoDestinoField;
        
        private string complementoEnderecoDestinoField;
        
        private string bairroDestinoField;
        
        private string cidadeDestinoField;
        
        private string uFDestinoField;
        
        private string sTODestinoField;
        
        private string nomeRecebedorField;
        
        private string documentoRecebedorField;
        
        private string obsRecebedorField;
        
        /// <remarks/>
        public long IdVolumeObjeto {
            get {
                return this.idVolumeObjetoField;
            }
            set {
                this.idVolumeObjetoField = value;
            }
        }
        
        /// <remarks/>
        public long IdEventoRastreio {
            get {
                return this.idEventoRastreioField;
            }
            set {
                this.idEventoRastreioField = value;
            }
        }
        
        /// <remarks/>
        public string TipoEvento {
            get {
                return this.tipoEventoField;
            }
            set {
                this.tipoEventoField = value;
            }
        }
        
        /// <remarks/>
        public int IdStatus {
            get {
                return this.idStatusField;
            }
            set {
                this.idStatusField = value;
            }
        }
        
        /// <remarks/>
        public int IdStatusEvento {
            get {
                return this.idStatusEventoField;
            }
            set {
                this.idStatusEventoField = value;
            }
        }
        
        /// <remarks/>
        public string DescricaoStatusEvento {
            get {
                return this.descricaoStatusEventoField;
            }
            set {
                this.descricaoStatusEventoField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DtEventoCompleta {
            get {
                return this.dtEventoCompletaField;
            }
            set {
                this.dtEventoCompletaField = value;
            }
        }
        
        /// <remarks/>
        public int IdGrupoStatusEvento {
            get {
                return this.idGrupoStatusEventoField;
            }
            set {
                this.idGrupoStatusEventoField = value;
            }
        }
        
        /// <remarks/>
        public string NomeGrupoStatusEvento {
            get {
                return this.nomeGrupoStatusEventoField;
            }
            set {
                this.nomeGrupoStatusEventoField = value;
            }
        }
        
        /// <remarks/>
        public string CodigoEdi {
            get {
                return this.codigoEdiField;
            }
            set {
                this.codigoEdiField = value;
            }
        }
        
        /// <remarks/>
        public long IdLocalEventoOrigem {
            get {
                return this.idLocalEventoOrigemField;
            }
            set {
                this.idLocalEventoOrigemField = value;
            }
        }
        
        /// <remarks/>
        public string LocalEvento {
            get {
                return this.localEventoField;
            }
            set {
                this.localEventoField = value;
            }
        }
        
        /// <remarks/>
        public string TipoEndereco {
            get {
                return this.tipoEnderecoField;
            }
            set {
                this.tipoEnderecoField = value;
            }
        }
        
        /// <remarks/>
        public string EnderecoEvento {
            get {
                return this.enderecoEventoField;
            }
            set {
                this.enderecoEventoField = value;
            }
        }
        
        /// <remarks/>
        public string ComplementoEnderecoEvento {
            get {
                return this.complementoEnderecoEventoField;
            }
            set {
                this.complementoEnderecoEventoField = value;
            }
        }
        
        /// <remarks/>
        public string BairroEvento {
            get {
                return this.bairroEventoField;
            }
            set {
                this.bairroEventoField = value;
            }
        }
        
        /// <remarks/>
        public string CidadeEvento {
            get {
                return this.cidadeEventoField;
            }
            set {
                this.cidadeEventoField = value;
            }
        }
        
        /// <remarks/>
        public string UFEvento {
            get {
                return this.uFEventoField;
            }
            set {
                this.uFEventoField = value;
            }
        }
        
        /// <remarks/>
        public string STOEvento {
            get {
                return this.sTOEventoField;
            }
            set {
                this.sTOEventoField = value;
            }
        }
        
        /// <remarks/>
        public long IdLocalEventoDestino {
            get {
                return this.idLocalEventoDestinoField;
            }
            set {
                this.idLocalEventoDestinoField = value;
            }
        }
        
        /// <remarks/>
        public string Destino {
            get {
                return this.destinoField;
            }
            set {
                this.destinoField = value;
            }
        }
        
        /// <remarks/>
        public string TipoEnderecoDestino {
            get {
                return this.tipoEnderecoDestinoField;
            }
            set {
                this.tipoEnderecoDestinoField = value;
            }
        }
        
        /// <remarks/>
        public string EnderecoDestino {
            get {
                return this.enderecoDestinoField;
            }
            set {
                this.enderecoDestinoField = value;
            }
        }
        
        /// <remarks/>
        public string ComplementoEnderecoDestino {
            get {
                return this.complementoEnderecoDestinoField;
            }
            set {
                this.complementoEnderecoDestinoField = value;
            }
        }
        
        /// <remarks/>
        public string BairroDestino {
            get {
                return this.bairroDestinoField;
            }
            set {
                this.bairroDestinoField = value;
            }
        }
        
        /// <remarks/>
        public string CidadeDestino {
            get {
                return this.cidadeDestinoField;
            }
            set {
                this.cidadeDestinoField = value;
            }
        }
        
        /// <remarks/>
        public string UFDestino {
            get {
                return this.uFDestinoField;
            }
            set {
                this.uFDestinoField = value;
            }
        }
        
        /// <remarks/>
        public string STODestino {
            get {
                return this.sTODestinoField;
            }
            set {
                this.sTODestinoField = value;
            }
        }
        
        /// <remarks/>
        public string NomeRecebedor {
            get {
                return this.nomeRecebedorField;
            }
            set {
                this.nomeRecebedorField = value;
            }
        }
        
        /// <remarks/>
        public string DocumentoRecebedor {
            get {
                return this.documentoRecebedorField;
            }
            set {
                this.documentoRecebedorField = value;
            }
        }
        
        /// <remarks/>
        public string ObsRecebedor {
            get {
                return this.obsRecebedorField;
            }
            set {
                this.obsRecebedorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.visualset.inf.br/")]
    public partial class ObjetoRastreio {
        
        private long idConhecimentoField;
        
        private string etiquetaPostagemField;
        
        private System.DateTime dtPostagemField;
        
        private long idUltimoStatusField;
        
        private int idGrupoStatusEventoField;
        
        private string nomeGrupoStatusEventoField;
        
        private long idStatusEntregaField;
        
        private short stPIField;
        
        private long idAoRemetenteField;
        
        private int stConhecimentoField;
        
        private EventoRastreio[] eventoRastreioField;
        
        private string statusSolicitacaoField;
        
        private Erro[] listaErrosField;
        
        /// <remarks/>
        public long IdConhecimento {
            get {
                return this.idConhecimentoField;
            }
            set {
                this.idConhecimentoField = value;
            }
        }
        
        /// <remarks/>
        public string EtiquetaPostagem {
            get {
                return this.etiquetaPostagemField;
            }
            set {
                this.etiquetaPostagemField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DtPostagem {
            get {
                return this.dtPostagemField;
            }
            set {
                this.dtPostagemField = value;
            }
        }
        
        /// <remarks/>
        public long IdUltimoStatus {
            get {
                return this.idUltimoStatusField;
            }
            set {
                this.idUltimoStatusField = value;
            }
        }
        
        /// <remarks/>
        public int IdGrupoStatusEvento {
            get {
                return this.idGrupoStatusEventoField;
            }
            set {
                this.idGrupoStatusEventoField = value;
            }
        }
        
        /// <remarks/>
        public string NomeGrupoStatusEvento {
            get {
                return this.nomeGrupoStatusEventoField;
            }
            set {
                this.nomeGrupoStatusEventoField = value;
            }
        }
        
        /// <remarks/>
        public long IdStatusEntrega {
            get {
                return this.idStatusEntregaField;
            }
            set {
                this.idStatusEntregaField = value;
            }
        }
        
        /// <remarks/>
        public short StPI {
            get {
                return this.stPIField;
            }
            set {
                this.stPIField = value;
            }
        }
        
        /// <remarks/>
        public long IdAoRemetente {
            get {
                return this.idAoRemetenteField;
            }
            set {
                this.idAoRemetenteField = value;
            }
        }
        
        /// <remarks/>
        public int StConhecimento {
            get {
                return this.stConhecimentoField;
            }
            set {
                this.stConhecimentoField = value;
            }
        }
        
        /// <remarks/>
        public EventoRastreio[] EventoRastreio {
            get {
                return this.eventoRastreioField;
            }
            set {
                this.eventoRastreioField = value;
            }
        }
        
        /// <remarks/>
        public string StatusSolicitacao {
            get {
                return this.statusSolicitacaoField;
            }
            set {
                this.statusSolicitacaoField = value;
            }
        }
        
        /// <remarks/>
        public Erro[] ListaErros {
            get {
                return this.listaErrosField;
            }
            set {
                this.listaErrosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.visualset.inf.br/")]
    public partial class ListarRastreio {
        
        private PerfilVipp perfilVippField;
        
        private string nrEtiquetaPostagemField;
        
        private string idConhecimentoField;
        
        private string observacaoUmField;
        
        private Erro[] listaErrosField;
        
        /// <remarks/>
        public PerfilVipp PerfilVipp {
            get {
                return this.perfilVippField;
            }
            set {
                this.perfilVippField = value;
            }
        }
        
        /// <remarks/>
        public string NrEtiquetaPostagem {
            get {
                return this.nrEtiquetaPostagemField;
            }
            set {
                this.nrEtiquetaPostagemField = value;
            }
        }
        
        /// <remarks/>
        public string IdConhecimento {
            get {
                return this.idConhecimentoField;
            }
            set {
                this.idConhecimentoField = value;
            }
        }
        
        /// <remarks/>
        public string ObservacaoUm {
            get {
                return this.observacaoUmField;
            }
            set {
                this.observacaoUmField = value;
            }
        }
        
        /// <remarks/>
        public Erro[] ListaErros {
            get {
                return this.listaErrosField;
            }
            set {
                this.listaErrosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.visualset.inf.br/")]
    public partial class LiberarDownload {
        
        private PerfilVipp perfilVippField;
        
        private string etiquetaField;
        
        private Erro[] listaErrosField;
        
        private short stLiberadoField;
        
        /// <remarks/>
        public PerfilVipp PerfilVipp {
            get {
                return this.perfilVippField;
            }
            set {
                this.perfilVippField = value;
            }
        }
        
        /// <remarks/>
        public string Etiqueta {
            get {
                return this.etiquetaField;
            }
            set {
                this.etiquetaField = value;
            }
        }
        
        /// <remarks/>
        public Erro[] ListaErros {
            get {
                return this.listaErrosField;
            }
            set {
                this.listaErrosField = value;
            }
        }
        
        /// <remarks/>
        public short StLiberado {
            get {
                return this.stLiberadoField;
            }
            set {
                this.stLiberadoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.visualset.inf.br/")]
    public partial class BloquearDownload {
        
        private PerfilVipp perfilVippField;
        
        private string etiquetaField;
        
        private short stBloqueadoField;
        
        private string descricaoField;
        
        private Erro[] listaErrosField;
        
        /// <remarks/>
        public PerfilVipp PerfilVipp {
            get {
                return this.perfilVippField;
            }
            set {
                this.perfilVippField = value;
            }
        }
        
        /// <remarks/>
        public string Etiqueta {
            get {
                return this.etiquetaField;
            }
            set {
                this.etiquetaField = value;
            }
        }
        
        /// <remarks/>
        public short StBloqueado {
            get {
                return this.stBloqueadoField;
            }
            set {
                this.stBloqueadoField = value;
            }
        }
        
        /// <remarks/>
        public string Descricao {
            get {
                return this.descricaoField;
            }
            set {
                this.descricaoField = value;
            }
        }
        
        /// <remarks/>
        public Erro[] ListaErros {
            get {
                return this.listaErrosField;
            }
            set {
                this.listaErrosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void BloquearObjetoCorreiosCompletedEventHandler(object sender, BloquearObjetoCorreiosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BloquearObjetoCorreiosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BloquearObjetoCorreiosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BloquearObjetoCorreios Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BloquearObjetoCorreios)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void BloquearDownloadConhecimentoCompletedEventHandler(object sender, BloquearDownloadConhecimentoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BloquearDownloadConhecimentoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BloquearDownloadConhecimentoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BloquearDownload Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BloquearDownload)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void LiberarDownloadConhecimentoCompletedEventHandler(object sender, LiberarDownloadConhecimentoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LiberarDownloadConhecimentoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LiberarDownloadConhecimentoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public LiberarDownload Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((LiberarDownload)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void ListarRastreioObjetoCompletedEventHandler(object sender, ListarRastreioObjetoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarRastreioObjetoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarRastreioObjetoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ObjetoRastreio[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ObjetoRastreio[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void PostarObjetoCompletedEventHandler(object sender, PostarObjetoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PostarObjetoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PostarObjetoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void PostarObjetoObjectCompletedEventHandler(object sender, PostarObjetoObjectCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PostarObjetoObjectCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PostarObjetoObjectCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PostagemRetorno Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PostagemRetorno)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void SolicitarEtiquetaCompletedEventHandler(object sender, SolicitarEtiquetaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SolicitarEtiquetaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SolicitarEtiquetaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RetornoEtiquetas Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RetornoEtiquetas)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591